# Generated by Django 4.2.6 on 2023-10-26 11:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0002_transcations_delete_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('language', models.CharField(max_length=10)),
                ('director_name', models.CharField(max_length=20)),
                ('hero_name', models.CharField(max_length=20)),
                ('genere', models.CharField(max_length=40)),
                ('country', models.CharField(max_length=10)),
                ('streaming_platform', models.CharField(max_length=20)),
                ('release_date', models.DateField(auto_now_add=True)),
                ('budget', models.IntegerField()),
                ('runtime', models.IntegerField()),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
            ],
        ),
        migrations.DeleteModel(
            name='Transcations',
        ),
    ]
