# Generated by Django 4.2.6 on 2023-10-26 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0003_movie_delete_transcations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('tel', 'Telugu'), ('hindi', 'Hindi'), ('tamil', 'Tamil')], default='tel', max_length=10),
        ),
    ]
