# Generated by Django 4.2.6 on 2023-10-26 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0005_alter_movie_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='runtime',
            field=models.DurationField(),
        ),
    ]
