# Generated by Django 4.2.6 on 2023-10-26 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0006_alter_movie_runtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='country',
            field=models.CharField(choices=[('IND', 'INDIA'), ('JAP', 'JAPAN'), ('RUS', 'RUSSIA'), ('USA', 'AMERICA')], default='IND', max_length=10),
        ),
    ]
