# Generated by Django 4.2.6 on 2023-10-26 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0007_alter_movie_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genere',
            field=models.CharField(choices=[('action', 'action'), ('comedy', 'comedy'), ('thriller', 'thriller'), ('romantic', 'romantic'), ('horror', 'horror'), ('drama', 'drama')], max_length=40),
        ),
    ]
